name: news_flutter
description: A new Flutter project.
version: 1.0.0+1

environment:
    sdk: '>=2.1.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^0.1.2
    carousel_slider: ^1.3.0

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    fonts:
        - family: TT Norms
          fonts:
              - asset: assets/fonts/TTNorms-Regular.otf
        - family: Merriweather
          fonts:
              - asset: assets/fonts/Merriweather-Regular.otf
